Add chat toggle in landscape for live streams
christfellowshipchurch/apollos-app pull request #167
Opened 2020-10-13 21:19 UTC by jordanwade

2020-10-19 21:04 UTC, jordanwade commented
FYI -  This needs a feature flag on it before it is merged.

2020-10-20 15:30 UTC, rkdavidson requested changes
I pushed a small commit 72b588d to refine the "Hide Chat" banner, but otherwise this is pretty good all things considered:
<img src="https://user-images.githubusercontent.com/1812955/96607366-4aa3b780-12c6-11eb-98a4-a71ceaf64621.jpg" width="380" />

**I found a major issue** on Android. I've seen this before on Crossroads, there's an issue with absolutely positioned/overlayed content and touch events on Android.
I screen recorded what happens on my Google Pixel 3A: https://photos.app.goo.gl/u15u5asgcDPq2YyP6

I think touch events "fall through" til they hit non-absolutely-positioned elements. You can see that tapping the toggle is actually hitting the app hamburger menu.

IMO, we should jettison the landscape chat toggle for Android for now.
There's no easy fix, and I question the value add. WDYT?

**There's a minor issue with watching count**, too — though this is probably existing issue, too. It gets tucked way up in the top right corner by the toggle, in landscape:
<img src="https://user-images.githubusercontent.com/1812955/96608303-36ac8580-12c7-11eb-87a9-f9e2e38164da.jpg" width="380" />
Probably simplest to hide it in landscape, yeah?

**Beyond that...**
I'm glad Apollos is imminently addressing the `<MediaPlayer>` in general, because this is easily a rabbit hole area and there's general bugginess with the layout beyond scope of this PR.

For ex. I get a different amount of padding to the right/around the controls UI depending on quirky things like whether I opened the app in landscape and changed it, or rotated when I got to the live stream player:

<img src="https://user-images.githubusercontent.com/1812955/96607028-ec76d480-12c5-11eb-97b8-cec0a860aad6.jpg" width="380" />

There's awkwardness — again, beyond scope of this PR — with the notch and safe bottom area, too.
I took a quick look and couldn't figure out why the `Chat` wasn't full bleed to the bottom here 👇, but it's not a show stopper. Just annoying in an OCD way.
<img src="https://user-images.githubusercontent.com/1812955/96607224-23e58100-12c6-11eb-8aab-05fcd45c5df6.jpg" width="380" />

2020-10-20 19:35 UTC, jordanwade commented
@rkdavidson I think I've addressed all the feedback I can. When you have time can you check this PR out again?

2020-10-21 13:47 UTC, rkdavidson approved these changes

2020-10-21 13:48 UTC, merged